language: java
sudo: false

jdk: oraclejdk8
install: true

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"


addons:
  apt:
    packages:
      - oracle-java8-installer
  sonarcloud:
    organization: "gurkenlabs-github"
    token:
      secure: G0KkiaIo+eBOrLgnvH5R6OLxhp7KWXEhP4VYuIo+yF0to4ZI3xLpmWL8ILQy9y//1QY6srbvTD6plpir3j7pToquko0GSpJwrcbQYjs+8WisH8f3WHFNGZoi3Y0BGwk3ozlcAwsxjpFvx/b1LPx5uPQpKNPaV35ag+IajholPXSwRi86/LvL12IxI5UgNfpEXwLiEquUJp9IGLGWFNT4Nb6TsZdD5EBerjkRJGyVV3MZvASiTLZLnV8CswFucbz5+SUBRmqNfSHzzryXnTwgFS7CNp3TRyNHWh5xBE2bbAvkgy3G/xSECQ3qUglxNleZ/AYqYyAbQfCX2q9WEwYD3OvZOZ3qyjzxdJ3NBa50KnKduiSF6GQDmmrUS6n6pu6R77NVz1fzkD4oz0Uny5BeiB5fkhn4rEVk9QmCOnfAFOj6MjSgFVTMGV3nmh6bHJlKhbHXPiYJAp7dwPWczOj2jevnJ4WO5yoNaAxHQWUMqkaukDjPkQGqF9/GPBElriOBM4CdQ/CGClpa82HexYuiGL+TCChZgcEWgBNLzt5BqMuckdVzmRB6AYXIJQZ0ZdTbDVIAioU6l08oDXM5Y3wd0yDTqKieIyof6lWqGc+hPdyN9wlY6BNGCR2g9wpUTBNPHXULVEixfnaeEUotd87hx26HC0wryuh+ZzY4GTCufQs=
before_install:
  - chmod +x gradlew

script: 
- ./gradlew fullbuild --scan -s
- sonar-scanner
- rm -f "$HOME/.gradle/caches/modules-2/modules-2.lock"
- rm -rf "$HOME/.gradle/caches/$GRADLE_VERSION/plugin-resolution"

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle/caches/'
    - '$HOME/.gradle/wrapper/'