name: Build

on:
  push:
    paths:
      - "**.gradle"
      - "**.kts"
      - "**.properties"
      - "**.java"
      - "**.xml"
      - ".github/workflows/*.yml"
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  fullbuild:
    runs-on: ubuntu-latest

    name: Java 17 build
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Install D-BUS AT-SPI core
        run: sudo apt-get -y install at-spi2-core

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: |
            build
            --scan
            -PskipSpotless

      - name: Test
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./gradlew jacocoTestReport -PskipSpotless

      - name: Package
        uses: gradle/gradle-build-action@v2
        with:
          arguments: jpackage

      - name: Gradle SonarQube Scan
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        if: ${{!github.event.pull_request.head.repo.fork}}
        with:
          arguments: |
            sonarqube
            -PskipSpotless
