name: Build

on:
  push:
    paths:
      - "**.gradle"
      - "**.properties"
      - "**.java"
      - "**.xml"
      - ".github/workflows/*.yml"
  pull_request:
    branches: [ master ]

jobs:
  fullbuild:
    runs-on: ubuntu-latest

    name: Java 8 build
    steps:
      - uses: actions/checkout@v2

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/'
            ~/.gradle/wrapper/'
          key: ${{ runner.os }}-gradle_cache

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Install D-BUS AT-SPI core
        run: sudo apt-get -y install at-spi2-core

      - name: Check Java Directory
        run: echo $JAVA_HOME

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle Fullbuild
        uses: GabrielBB/xvfb-action@v1
        with:
          run: ./gradlew fullbuild

  sonarcloud:
    runs-on:
      ubuntu-latest
    name: Static Analysis
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up JDK 15
        uses: actions/setup-java@v2
        with:
          java-version: '15'
          distribution: 'adopt'

      - name: Maven repo and sonar cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2/repository'
            ~/.sonar/cache'
          key: ${{ runner.os }}-mvn_sonar_cache

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches/'
            ~/.gradle/wrapper/'
          key: ${{ runner.os }}-gradle_cache

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Gradle SonarQube Scan
        uses: GabrielBB/xvfb-action@v1
        run: ./gradlew test jacocoTestReport sonarqube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


