name: Release LITIENGINE

on:
  workflow_dispatch

jobs:
  gradle:
    name: Release build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 10
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19

      - name: Prepare & publish release
        uses: gradle/gradle-build-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
          NEXUS_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          NEXUS_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
        with:
          arguments: |
            prepareVote
            publishRelease
            --info
            -x test
            -Prc=1
            -Pgh
            -Prelease=true
            -PskipJavadoc
            -PskipSpotless
            -PghGitSourceUsername=gurkenlabs
            -PghGitSourcePassword=$GITHUB_TOKEN
            -PghNexusUsername=$NEXUS_USERNAME
            -PghNexusPassword=$NEXUS_PASSWORD
            -PuseInMemoryKey=true
            -Psigning.inMemoryKey=$GPG_SIGNING_KEY
            -Psigning.password=$GPG_PASSPHRASE
