name: Release LITIENGINE

on:
  workflow_dispatch:
    inputs:
      incrementVersion:
        type: choice
        description: "increment version?"
        required: true
        default: 'none'
        options:
          - none
          - patch
          - minor
          - major
  schedule:
    # Midnight every day
    - cron: "0 0 * * *"

jobs:
  gradle:
    name: Release build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 19
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19
      - name: Print project version
        uses: gradle/gradle-build-action@v2
        with:
          arguments: printGitSemVer
      - name: Increment patch version
        if: inputs.incrementVersion == 'patch'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: incrementPatchVersion
      - name: Increment minor version
        if: inputs.incrementVersion == 'minor'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: incrementMinorVersion
      - name: Increment major version
        if: inputs.incrementVersion == 'major'
        uses: gradle/gradle-build-action@v2
        with:
          arguments: incrementMajorVersion
      - name: Publish
        uses: gradle/gradle-build-action@v2
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.OSSRH_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.OSSRH_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.PGP_SECRET }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.PGP_PASSPHRASE }}
        with:
          arguments: |
            publishToSonatype closeSonatypeStagingRepository
