name: Spotless

on: [ push, pull_request ]

jobs:
  autostyle:
    name: "Spotless"
    runs-on: ubuntu-latest
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - uses: actions/checkout@v2
      - uses: gradle/gradle-build-action@v2
        with:
          arguments: spotlessCheck
